language: node_js
node_js:
  - '12.0.0'

cache:
  directories:
    - node_modules

install:
  - yarn install --frozen-lockfile --non-interactive

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && chmod +x publish.sh && ./publish.sh
